### ISSUE TITLE
Error in the first load of the app

### ISSUE THREAD

**Issue by gescudero** [clvLabs/fortnitetracker-stats#15]
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/fortnitetracker-stats/app/src/lib/task.py", line 63, in _threadhandler
    self.taskLoop()
  File "/fortnitetracker-stats/app/src/apiprofilesgetter.py", line 57, in taskLoop
    self.getProfileFromTrn(username, trn_username, platform)
  File "/fortnitetracker-stats/app/src/apiprofilesgetter.py", line 90, in getProfileFromTrn
    self.stats.add_stats_from_trn_dict(username, trn_profile_actual_dict)
  File "/fortnitetracker-stats/app/src/model/stats.py", line 51, in add_stats_from_trn_dict
    last_match_date = datetime.strptime(trn_data["recentMatches"][0]["dateCollected"], "%Y-%m-%dT%H:%M:%S")
IndexError: list index out of range
```

**Comment by gescudero** [comment]
solved
